// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cosqgqyvgbzziaozstml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvc3FncXl2Z2J6emlhb3pzdG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njc1MzQsImV4cCI6MjA2OTA0MzUzNH0.RRSWnVz97omUv1BOVeykmuoGapb7YXqCfmz03kae7WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});